### ISSUE TITLE
unable to connect to hbase server using rpc client

### ISSUE THREAD

**Issue by RAKESH1256** [falsecz/hbase-rpc-client#11]
below code is throwing error 
'use strict';
require('coffee-script/register');

-------error---------------
"C:\Program Files (x86)\JetBrains\WebStorm 10.0.4\bin\runnerw.exe" "C:\Program Files (x86)\nodejs\node.exe" --debug-brk=2378 --nolazy server.js
Debugger listening on port 2378
module.js:338
    throw err;
          ^
Error: Cannot find module 'coffee-script/register'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Drive\Code\Learning\NJS_HBASE\NJS_HBASE_JAVAAPI\server.js:4:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.runMain [as _onTimeout] (module.js:501:10)

Process finished with exit code 1

**Comment by falsecz** [comment]
Hi, try 0.1.2 (version without coffee-script)

**Comment by lironess** [comment]
works :)

2015-08-19 12:22 GMT+03:00 Lukas Benes <notifications@github.com>:
