### ISSUE TITLE
Get causes java.lang.NullPointerException

### ISSUE THREAD

**Issue by shekenahglory** [falsecz/hbase-rpc-client#33]
I'm guessing this is not an issue with the code, but I can't figure it out - any suggestions?  It looks like the scan on `hbase:meta` causes the exception.

```
process.env.DEBUG= 'hbase*';

var hbase = require('hbase-rpc-client');

var client = hbase({
  zookeeperHosts: ['hbase.ripple.com'],
    zookeeperRoot: "/hbase",
    zookeeperReconnectTimeout: 60000,
    rootRegionZKPath: "/meta-region-server",
    rpcTimeout: 90000,
    callTimeout: 60000,
    tcpNoDelay: true,
    tcpKeepAlive: true
});

var get = new hbase.Get('last_validated');

client.get('prod_control', get, function(err, resp) {
  console.log(err.stackTrace, resp);
});
```

output:
```
  hbase-client get on table: prod_control get: {"row":"last_validated","tr":{"from":null,"to":null},"familyMap":{},"maxVersions":1} +0ms
  hbase-region locateRegion table: prod_control row: last_validated +2ms
  hbase-region getRegionConnection +403ms hadoop3-private.wdc01.infra.ripple.com:60020
  hbase-region getRegionConnection connecting to hadoop3-private.wdc01.infra.ripple.com:60020 +1ms
  hbase-connection connecting to connection(hadoop3-private.wdc01.infra.ripple.com:60020) id: 0 +0ms
  hbase-connection connected to connection(hadoop3-private.wdc01.infra.ripple.com:60020) id: 0 +120ms
  hbase-region hadoop3-private.wdc01.infra.ripple.com:60020 connected, total 1 connections +5ms
  hbase-region locateRegionInMeta table: prod_control row: last_validated +1ms
  hbase-client prefetchRegionCache for table: prod_control +1ms
  hbase-region locateRegion table: hbase:meta row: prod_control,,00000000000000 +1ms
  hbase-region locateRegionInMeta table: hbase:meta row: prod_control,,00000000000000 +0ms
  hbase-region getRegionConnection +0ms hadoop3-private.wdc01.infra.ripple.com:60020
  hbase-region getRegionConnection from cache (servers: 1), hadoop3-private.wdc01.infra.ripple.com:60020 +1ms
  hbase-client scan on: hbase:meta row: 1 region: hbase:meta,,1 startRow: prod_control,,00000000000000 stopRow: prod_controm,,00000000000000 +0ms
  hbase-call operation 1 (Scan) called +4ms
  hbase-call operation 1 (Scan) completed. Took: 133ms +133ms
java.io.IOException
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2069)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:107)
	at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:130)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:107)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException

  hbase-region Trying to find cached regionLocation for table prod_control +3ms
{}
  hbase-region Couldn't find cached regionLocation for table prod_control +1ms
  hbase-region getRegionConnection +0ms hadoop3-private.wdc01.infra.ripple.com:60020
  hbase-region getRegionConnection from cache (servers: 1), hadoop3-private.wdc01.infra.ripple.com:60020 +0ms
  hbase-call operation 2 (Get) called +1ms
  hbase-call operation 2 (Get) completed. Took: 127ms +127ms
  hbase-region locateRegionInMeta error: .ExceptionResponse +1ms
java.io.IOException
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2069)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:107)
	at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:130)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:107)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
```

**Comment by wision** [comment]
What version of hbase do you use? Is there anything in region server logs?

**Comment by shekenahglory** [comment]
hbase 1.0
CDH build

**Comment by shekenahglory** [comment]
```
Unexpected throwable object 
java.lang.NullPointerException
    at org.apache.hadoop.hbase.quotas.RegionServerQuotaManager.checkQuota(RegionServerQuotaManager.java:182)
    at org.apache.hadoop.hbase.quotas.RegionServerQuotaManager.checkQuota(RegionServerQuotaManager.java:136)
    at org.apache.hadoop.hbase.regionserver.RSRpcServices.scan(RSRpcServices.java:2131)
    at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:31443)
    at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2035)
    at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:107)
    at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:130)
    at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:107)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by wision** [comment]
Some people did encounter problems with CDH builds before (cloudera backported some features from hbase 1.1.x to 1.0.x afaik), but unfortunatelly I'm not able to get CDH image now. I'll try to test it during next week.

**Comment by wision** [comment]
@shekenahglory Sorry I forgot about this issue.. meanwhile hbase-rpc-client does support hbase@1.2.x. Is this still an issue?

**Comment by shekenahglory** [comment]
I don't know, we went with a different solution.
