### ISSUE TITLE
can't find config info

### ISSUE THREAD

**Issue by rajkaran** [falsecz/hbase-rpc-client#54]
Where to find this info
```
       zookeeperHosts: ["whhdp03.wh.tvh.ca:2181"] # required
    	zookeeperRoot: "/hbase"
    	zookeeperReconnectTimeout: 20000
    	rootRegionZKPath: "/meta-region-server" 
```
I have zookeeper client on every host so which host will come here or all of them?
I do not find zookeeperRoot in zoo.cfg file where it suppose to be?
Where to find rootRegionZKPath?

And which users are these
```
        realUser: "someRealUser"
	effectiveUser: "someEffectiveUser"
```

**Comment by wision** [comment]
You should put there all your zookeeper hosts.. for example:
```
zookeeperHosts: ["whhdp01.wh.tvh.ca,whhdp02.wh.tvh.ca,whhdp03.wh.tvh.ca"] 
```
If you did not change zookeeperRoot and rootRegionZKPath, then you don't need to configure it and the client will use default values.

User values are required by hbase 1.2.x and are used for authentication.

**Comment by rajkaran** [comment]
```
zookeeperHosts: ["whhdp03.wh.tvh.ca:2181", "whhdp01.wh.tvh.ca:2181", "whhdp02.wh.tvh.ca:2181"] # required
        zookeeperRoot: "/hbase"
        zookeeperReconnectTimeout: 20000
        rootRegionZKPath: "/meta-region-server"
        rpcTimeout: 30000
        callTimeout: 5000
        tcpNoDelay: "no"
        tcpKeepAlive: "yes"
```

This is my config now.

It is still throwing error...
```
{ Exception: NO_NODE[-101]
    at ConnectionManager.onSocketData (/var/www/html/coffee-loopback/node_modules/node-zookeeper-client/lib/ConnectionManager.js:570:35)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)

  code: -101,
  name: 'NO_NODE',
  path: undefined,
  message: 'Exception: NO_NODE[-101]' }
```

**Comment by wision** [comment]
NO_NODE means that requested node does not exist. Can you check your hbase configuration, if it's /hbase? Or connect to you zookeeper and see for yourself.

**Comment by rajkaran** [comment]
I do have access to hbase-site.xml file but which property's value is this?
```
<property>
	<name>zookeeper.znode.parent</name>
	<value>/hbase-unsecure</value>
	<source>hbase-site.xml</source>
</property>

<property>
	<name>hbase.zookeeper.property.dataDir</name>
	<value>${hbase.tmp.dir}/zookeeper</value>
	<source>hbase-default.xml</source>
</property>

<property>
	<name>hbase.zookeeper.quorum</name>
	<value>
		whhdp03.wh.tvh.ca,whhdp01.wh.tvh.ca,whhdp02.wh.tvh.ca
	</value>
	<source>hbase-site.xml</source>
</property>

<property>
	<name>zookeeper.znode.rootserver</name>
	<value>root-region-server</value>
	<source>hbase-default.xml</source>
</property>

<property>
	<name>hbase.config.read.zookeeper.config</name>
	<value>false</value>
	<source>hbase-default.xml</source>
</property>

<property>
	<name>hbase.zookeeper.property.clientPort</name>
	<value>2181</value>
	<source>hbase-site.xml</source>
</property>
```
It is Horton works installation..

**Comment by wision** [comment]
You should try rootRegionZKPath: "/root-region-server"

**Comment by rajkaran** [comment]
No still not working

**Comment by wision** [comment]
What version of hbase do you use?

**Comment by rajkaran** [comment]
hbase1.1.2

**Comment by rajkaran** [comment]
We do see a connection to Datanodes but it drops right away..

**Comment by wision** [comment]
Connect to your zookeeper and what do you see after typing `ls /`?

**Comment by rajkaran** [comment]
By connect you mean SSH to host which has zookeeper client?

If that's the case, which directory list I am checking

**Comment by wision** [comment]
I mean connect via zookeeper client and list nodes on the root path.

**Comment by rajkaran** [comment]
I am still not sure what you mean... :(

I can go to Ambari to list all nodes.
I can SSH to all nodes.
We have Zookeeper client and server running on all nodes (whhdp01, whhdp02, whhdp03).
Hbase is installed on whhdp03.

So if you want listing of root directory of any of them I can get it.

**Comment by rajkaran** [comment]
Here is it
```
[zk: whhdp03.wh.tvh.ca:2181(CONNECTED) 1] ls /
[registry, controller, brokers, zookeeper, infra-solr, hbase-unsecure, admin, isr_change_notification, controller_epoch, hiveserver2, rmstore, solr, consumers, config]
```

**Comment by wision** [comment]
What does `ls /hbase-unsecure` show?

**Comment by rajkaran** [comment]
```
[zk: whhdp03.wh.tvh.ca:2181(CONNECTED) 0] ls /hbase-unsecure 
[replication, meta-region-server, rs, splitWAL, backup-masters, table-lock, flush-table-proc, master-maintenance, region-in-transition, online-snapshot, switch, master, running, recovering-regions, draining, namespace, hbaseid, table]

```

**Comment by wision** [comment]
Then your config should look like this: ```
	zookeeperHosts: ["whhdp01.wh.tvh.ca,whhdp02.wh.tvh.ca,whhdp03.wh.tvh.ca"]
	zookeeperRoot: "/hbase-unsecure"
```

**Comment by rajkaran** [comment]
So here is my config now

```
client = hbase
        zookeeperHosts: ["whhdp03.wh.tvh.ca,whhdp01.wh.tvh.ca,whhdp02.wh.tvh.ca"] # required
        zookeeperRoot: "/hbase-unsecure"
        zookeeperReconnectTimeout: 20000
        rootRegionZKPath: "/root-region-server"
        rpcTimeout: 30000
        callTimeout: 5000
        tcpNoDelay: "no"
        tcpKeepAlive: "yes"
```

**Comment by wision** [comment]
Either don't set rootRegionZKPath (to make it use default, which is meta-region-server) or set it to meta-region-server.

**Comment by rajkaran** [comment]
Now I have connection with

```
client = hbase
        zookeeperHosts: ["whhdp03.wh.tvh.ca,whhdp01.wh.tvh.ca,whhdp02.wh.tvh.ca"] # required
        zookeeperRoot: "/hbase-unsecure"
        zookeeperReconnectTimeout: 20000
        rootRegionZKPath: "/meta-region-server"
        rpcTimeout: 30000
        callTimeout: 5000
        tcpNoDelay: "no"
        tcpKeepAlive: "yes"
```

**Comment by wision** [comment]
That should be fine.
