### ISSUE TITLE
Illegal wire type of unknown field 13 in Message .MetaRegionServer

### ISSUE THREAD

**Issue by nick** [falsecz/hbase-rpc-client#8]
I'm getting this error when trying to connect:

    /project-code/node_modules/hbase-rpc-client/node_modules/protobufjs/ProtoBuf.js:2104
                                throw(e);
                                      ^
    Error: Illegal wire type of unknown field 13 in Message .MetaRegionServer#decode: 7
      at [object Object].ProtoBuf.Reflect.Message.decode (/project-code/node_modules/hbase-rpc-client/node_modules/protobufjs/ProtoBuf.js:2289:39)
      at Function.Message.decode (/project-code/node_modules/hbase-rpc-client/node_modules/protobufjs/ProtoBuf.js:2099:41)
      at Object.exports.decodeMeta (/project-code/node_modules/hbase-rpc-client/lib/zk-protobuf.coffee:20:25)
      at ZooKeeperWatcher.<anonymous> (/project-code/node_modules/hbase-rpc-client/lib/client.coffee:75:25)
      at ZooKeeperWatcher.emit (events.js:106:17)
      at /project-code/node_modules/hbase-rpc-client/node_modules/zookeeper-watcher/node_modules/node-zookeeper-client/index.js:165:26
      at Object.async.whilst (/project-code/node_modules/hbase-rpc-client/node_modules/zookeeper-watcher/node_modules/node-zookeeper-client/node_modules/async/lib/async.js:627:13)
      at /project-code/node_modules/hbase-rpc-client/node_modules/zookeeper-watcher/node_modules/node-zookeeper-client/node_modules/async/lib/async.js:623:23
      at /project-code/node_modules/hbase-rpc-client/node_modules/zookeeper-watcher/node_modules/node-zookeeper-client/index.js:145:21
      at Object.callback (/project-code/node_modules/hbase-rpc-client/node_modules/zookeeper-watcher/node_modules/node-zookeeper-client/index.js:582:17)
      at ConnectionManager.onSocketData (/project-code/node_modules/hbase-rpc-client/node_modules/zookeeper-watcher/node_modules/node-zookeeper-client/lib/ConnectionManager.js:562:35)
      at Socket.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)

The connection code I'm using:

    require('coffee-script/register');
    var hbase = require("hbase-rpc-client");

    var client = hbase({
        zookeeperHosts: [ "localhost:2181" ],
        zookeeperRoot: "/hbase",
        rootRegionZKPath: "/root-region-server",
    });

    client.on("error", function(err) {
        console.log("hbase client error:", err);
    });

Any help appreciated!

**Comment by wision** [comment]
What's your hbase and zookeeper version?

**Comment by wision** [comment]
Also, rootRegionZKPath should be "/meta-region-server".

**Comment by nick** [comment]
Ah I'm using 0.94 of hbase which I guess is too old. Zookeeper is version 3.4.5

**Comment by wision** [comment]
Indeed, 0.94 doesn't support protocol buffers which are used in this client. You should use https://www.npmjs.com/package/hbase-client which should work for you.

**Comment by wanming** [comment]
I'm getting this error when trying to connect:
Error: Illegal wire type of unknown field 5 in Message .MetaRegionServer#decode: 4
My hbase version is 1.2.4. using docker: https://github.com/dajobe/hbase-docker
same problem?
