### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by zhaomizhi** [falsecz/hbase-rpc-client#9]
Every time I add the line "hbase = require "hbase-rpc-client", and then run coffee -c server.coffee, it generate server.js. After I fun node server.js, it always throw exception: 

 
/Users/Aki/Desktop/node/node_modules/hbase-rpc-client/index.coffee:4
module.exports = (options) ->
                            ^
SyntaxError: Unexpected token >
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Aki/Desktop/node/server.js:5:11)
    at Object.<anonymous> (/Users/Aki/Desktop/node/server.js:7:4)
    at Module._compile (module.js:460:26)

Please, is there somebody knows what is the error coming?

**Comment by wision** [comment]
@zhaomizhi Try using register:
```
require "coffee-script/register"
hbase = require "hbase-rpc-client"
```
If that doesn't help, please post whole coffee-script code.

**Comment by zhaomizhi** [comment]
Yes, it solved. Thanks so much!

**Comment by wision** [comment]
You're welcome.
